sudo: false

language: python3

install:
  - apt-get install python3-pip
  - pip3 install requests
  - pip3 install rsa
  - pip3 install thrift==0.11.0
  - pip3 install urllib3
  - pip3 install bs4
  - pip3 install gtts
  - pip3 install googletrans
  - pip3 install beautifulsoup
  - pip3 install pytz  
  - pip3 install humanfriendly
  
script:
  - python3 cmg.py

after_success:
  - python3
